CREATE TABLE IF NOT EXISTS assistant_codex_forward_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_run_id CHAR(36) CHARACTER SET ascii NOT NULL,
  request_key_hash CHAR(64) CHARACTER SET ascii NULL,
  request_hash CHAR(64) CHARACTER SET ascii NULL,
  caller_id VARCHAR(128) NOT NULL DEFAULT '',
  execution_namespace VARCHAR(191) NOT NULL DEFAULT '',
  delivery_mode VARCHAR(16) CHARACTER SET ascii NOT NULL DEFAULT 'bridge',
  message_id VARCHAR(191) NOT NULL,
  chat_id VARCHAR(191) NOT NULL,
  chat_type VARCHAR(64) NOT NULL DEFAULT '',
  message_type VARCHAR(64) NOT NULL DEFAULT '',
  sender_open_id VARCHAR(191) NOT NULL DEFAULT '',
  sender_name VARCHAR(255) NOT NULL DEFAULT '',
  conversation_scope VARCHAR(64) NOT NULL DEFAULT '',
  prompt MEDIUMTEXT NOT NULL,
  group_chat_context_json MEDIUMTEXT NOT NULL,
  context_entries_json MEDIUMTEXT NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  reply_attempts INT NOT NULL DEFAULT 0,
  lease_owner VARCHAR(191) NOT NULL DEFAULT '',
  lease_expires_at BIGINT NULL,
  next_attempt_at BIGINT NULL,
  started_at BIGINT NULL,
  finished_at BIGINT NULL,
  reply_sent_at BIGINT NULL,
  result_json MEDIUMTEXT NOT NULL,
  last_error TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY ux_forward_public_run (public_run_id),
  UNIQUE KEY ux_forward_request_key (request_key_hash),
  UNIQUE KEY ux_forward_message (message_id),
  KEY idx_forward_status_next (status,next_attempt_at,id),
  KEY idx_forward_lease (status,lease_expires_at,id),
  KEY idx_forward_chat_created (chat_id,created_at,id),
  KEY idx_forward_caller_created (caller_id,created_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assistant_inbound_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  message_id VARCHAR(191) NOT NULL,
  chat_id VARCHAR(191) NOT NULL,
  chat_type VARCHAR(64) NOT NULL DEFAULT '',
  message_type VARCHAR(64) NOT NULL DEFAULT '',
  sender_open_id VARCHAR(191) NOT NULL DEFAULT '',
  sender_name VARCHAR(255) NOT NULL DEFAULT '',
  content_text MEDIUMTEXT NOT NULL,
  content_json MEDIUMTEXT NOT NULL,
  mentions_json MEDIUMTEXT NOT NULL,
  raw_event_json MEDIUMTEXT NOT NULL,
  bot_mentioned TINYINT(1) NOT NULL DEFAULT 0,
  group_context_candidate TINYINT(1) NOT NULL DEFAULT 0,
  codex_context_session_id VARCHAR(191) NOT NULL DEFAULT '',
  codex_context_turn_id VARCHAR(191) NOT NULL DEFAULT '',
  codex_context_forwarded_at BIGINT NULL,
  message_created_at BIGINT NULL,
  message_updated_at BIGINT NULL,
  received_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY ux_inbound_message (message_id),
  KEY idx_inbound_chat_created (chat_id,message_created_at,id),
  KEY idx_inbound_context (chat_id,group_context_candidate,codex_context_forwarded_at,message_created_at,id),
  KEY idx_inbound_received (received_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assistant_message_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  message_id VARCHAR(191) NOT NULL,
  chat_id VARCHAR(191) NOT NULL,
  event VARCHAR(64) NOT NULL,
  ok TINYINT(1) NOT NULL,
  reason TEXT NOT NULL,
  detail TEXT NOT NULL,
  chat_type VARCHAR(64) NOT NULL,
  message_type VARCHAR(64) NOT NULL,
  elapsed_ms BIGINT NULL,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (id),
  KEY idx_message_events_created (created_at,id),
  KEY idx_message_events_message (message_id,event,id),
  KEY idx_message_events_chat (chat_id,created_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
