ALTER TABLE assistant_codex_sessions ADD COLUMN connection_id VARCHAR(128) NULL;
ALTER TABLE assistant_codex_events ADD COLUMN connection_id VARCHAR(128) NULL;
ALTER TABLE assistant_codex_forward_jobs ADD COLUMN connection_id VARCHAR(128) NULL;
ALTER TABLE assistant_inbound_messages ADD COLUMN connection_id VARCHAR(128) NULL;
ALTER TABLE assistant_message_events ADD COLUMN connection_id VARCHAR(128) NULL;
ALTER TABLE assistant_codex_sessions MODIFY COLUMN connection_id VARCHAR(128) NOT NULL;
ALTER TABLE assistant_codex_events MODIFY COLUMN connection_id VARCHAR(128) NOT NULL;
ALTER TABLE assistant_codex_forward_jobs MODIFY COLUMN connection_id VARCHAR(128) NOT NULL;
ALTER TABLE assistant_inbound_messages MODIFY COLUMN connection_id VARCHAR(128) NOT NULL;
ALTER TABLE assistant_message_events MODIFY COLUMN connection_id VARCHAR(128) NOT NULL;
ALTER TABLE assistant_codex_sessions DROP INDEX ux_assistant_codex_sessions_actor;
ALTER TABLE assistant_codex_sessions ADD UNIQUE INDEX ux_assistant_codex_sessions_actor (connection_id,feishu_open_id,chat_id);
ALTER TABLE assistant_codex_sessions DROP INDEX idx_assistant_codex_sessions_codex;
ALTER TABLE assistant_codex_sessions ADD INDEX idx_assistant_codex_sessions_codex (connection_id,codex_session_id);
ALTER TABLE assistant_codex_sessions DROP INDEX idx_assistant_codex_sessions_updated;
ALTER TABLE assistant_codex_sessions ADD INDEX idx_assistant_codex_sessions_updated (connection_id,updated_at DESC);
ALTER TABLE assistant_codex_events DROP INDEX ux_assistant_codex_events_key;
ALTER TABLE assistant_codex_events ADD UNIQUE INDEX ux_assistant_codex_events_key (connection_id,codex_session_id,event_key);
ALTER TABLE assistant_codex_events DROP INDEX idx_assistant_codex_events_session;
ALTER TABLE assistant_codex_events ADD INDEX idx_assistant_codex_events_session (connection_id,codex_session_id,created_at,id);
ALTER TABLE assistant_codex_events DROP INDEX idx_assistant_codex_events_chat;
ALTER TABLE assistant_codex_events ADD INDEX idx_assistant_codex_events_chat (connection_id,chat_id,created_at);
ALTER TABLE assistant_codex_events DROP INDEX idx_assistant_codex_events_public;
ALTER TABLE assistant_codex_events ADD INDEX idx_assistant_codex_events_public (connection_id,feishu_open_id(120),chat_id(120),codex_session_id(120),message_id(120),id);
ALTER TABLE assistant_codex_events DROP INDEX idx_assistant_codex_events_progress;
ALTER TABLE assistant_codex_events ADD INDEX idx_assistant_codex_events_progress (connection_id,feishu_open_id(120),chat_id(120),codex_session_id(120),message_id(120),created_at,id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX ux_forward_request_key;
ALTER TABLE assistant_codex_forward_jobs ADD UNIQUE INDEX ux_forward_request_key (connection_id,request_key_hash);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX ux_forward_message;
ALTER TABLE assistant_codex_forward_jobs ADD UNIQUE INDEX ux_forward_message (connection_id,message_id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX idx_forward_status_next;
ALTER TABLE assistant_codex_forward_jobs ADD INDEX idx_forward_status_next (connection_id,status,next_attempt_at,id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX idx_forward_lease;
ALTER TABLE assistant_codex_forward_jobs ADD INDEX idx_forward_lease (connection_id,status,lease_expires_at,id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX idx_forward_feedback_cleanup;
ALTER TABLE assistant_codex_forward_jobs ADD INDEX idx_forward_feedback_cleanup (connection_id,feedback_cleanup_pending,feedback_cleanup_at,id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX idx_forward_chat_created;
ALTER TABLE assistant_codex_forward_jobs ADD INDEX idx_forward_chat_created (connection_id,chat_id,created_at,id);
ALTER TABLE assistant_codex_forward_jobs DROP INDEX idx_forward_caller_created;
ALTER TABLE assistant_codex_forward_jobs ADD INDEX idx_forward_caller_created (connection_id,caller_id,created_at,id);
ALTER TABLE assistant_inbound_messages DROP INDEX ux_inbound_message;
ALTER TABLE assistant_inbound_messages ADD UNIQUE INDEX ux_inbound_message (connection_id,message_id);
ALTER TABLE assistant_inbound_messages DROP INDEX idx_inbound_chat_created;
ALTER TABLE assistant_inbound_messages ADD INDEX idx_inbound_chat_created (connection_id,chat_id,message_created_at,id);
ALTER TABLE assistant_inbound_messages DROP INDEX idx_inbound_context;
ALTER TABLE assistant_inbound_messages ADD INDEX idx_inbound_context (connection_id,chat_id,group_context_candidate,codex_context_forwarded_at,message_created_at,id);
ALTER TABLE assistant_inbound_messages DROP INDEX idx_inbound_received;
ALTER TABLE assistant_inbound_messages ADD INDEX idx_inbound_received (connection_id,received_at,id);
ALTER TABLE assistant_message_events DROP INDEX idx_message_events_created;
ALTER TABLE assistant_message_events ADD INDEX idx_message_events_created (connection_id,created_at,id);
ALTER TABLE assistant_message_events DROP INDEX idx_message_events_message;
ALTER TABLE assistant_message_events ADD INDEX idx_message_events_message (connection_id,message_id,event,id);
ALTER TABLE assistant_message_events DROP INDEX idx_message_events_chat;
ALTER TABLE assistant_message_events ADD INDEX idx_message_events_chat (connection_id,chat_id,created_at,id);
ALTER TABLE bridge_jobs DROP INDEX jobs_claim;
ALTER TABLE bridge_jobs ADD INDEX jobs_claim (connection_id,kind,status,next_attempt_at,created_at);
ALTER TABLE bridge_jobs DROP INDEX jobs_lease;
ALTER TABLE bridge_jobs ADD INDEX jobs_lease (connection_id,status,lease_expires_at);
ALTER TABLE bridge_outbox DROP INDEX outbox_claim;
ALTER TABLE bridge_outbox ADD INDEX outbox_claim (connection_id,status,next_attempt_at,created_at);
ALTER TABLE bridge_outbox DROP INDEX outbox_lease;
ALTER TABLE bridge_outbox ADD INDEX outbox_lease (connection_id,status,lease_expires_at);
ALTER TABLE bridge_outbox DROP INDEX outbox_cleanup;
ALTER TABLE bridge_outbox ADD INDEX outbox_cleanup (connection_id,cleanup_pending,id);
ALTER TABLE bridge_recoveries DROP INDEX recovery_claim;
ALTER TABLE bridge_recoveries ADD INDEX recovery_claim (connection_id,status,lease_expires_at,created_at,id);
ALTER TABLE bridge_recoveries DROP INDEX recovery_idempotency;
ALTER TABLE bridge_recoveries ADD UNIQUE INDEX recovery_idempotency (connection_id,caller_id,idempotency_key);
